apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: client-apps-certificate
  namespace: default
spec:
  secretName: client-apps-certificate
  issuerRef:
    name: client-apps-issuer
  dnsNames:
  - preproduction.resourcewatch.org
  - south-africa-platform.vizzuality.com
  - indonesia-platform-staging.vizzuality.com
  - india-platform-staging.vizzuality.com


