apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  schedule: "35 01 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubecron
              image: vizzuality/kubecron:1.0.22
              imagePullPolicy: Always
              env:
                - name: GCLOUD_BACKUPS_CREDENTIALS
                  valueFrom:
                    secretKeyRef:
                      name: mssecrets
                      key: GCLOUD_BACKUPS_CREDENTIALS
                - name: CT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: mssecrets
                      key: CT_TOKEN
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dbsecrets
                      key: POSTGRES_PASSWORD
                - name: CT_MONGO_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: dbsecrets
                      key: CT_MONGO_ADMIN_USER
                - name: CT_MONGO_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dbsecrets
                      key: CT_MONGO_ADMIN_PASSWORD
              args:
                - mongo
          restartPolicy: OnFailure
