apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongo-ct-backup
  namespace: gateway
spec:
  schedule: "35 01 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubecron
              image: vizzuality/kubecron:1.0.41-aws
              imagePullPolicy: Always
              env:
                - name: AWS_BACKUPS_BUCKET_URI
                  valueFrom:
                    secretKeyRef:
                      name: backups
                      key: AWS_BACKUPS_BUCKET_URI
                - name: CT_MONGO_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: backups
                      key: CT_MONGO_ADMIN_USER
                - name: CT_MONGO_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backups
                      key: CT_MONGO_ADMIN_PASSWORD
              args:
                - mongo-ct
          restartPolicy: OnFailure
