apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: core
spec:
  schedule: "00 15 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubecron
              image: vizzuality/kubecron:1.0.38
              imagePullPolicy: Always
              env:
                - name: AWS_BACKUPS_BUCKET_URI
                  valueFrom:
                    secretKeyRef:
                      name: backups
                      key: AWS_BACKUPS_BUCKET_URI
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backups
                      key: POSTGRES_PASSWORD
              args:
                - postgres
          restartPolicy: OnFailure
