apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  namespace: core
  labels:
    type: elasticsearch
    component: elasticsearch
    role: master
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: elasticsearch
        component: elasticsearch
        role: master
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - elasticsearch
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - master
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: es-master
          securityContext:
            privileged: false
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: quay.io/pires/docker-elasticsearch-kubernetes:5.5.2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "DISCOVERY_SERVICE"
              value: "elasticsearch-master"
            - name: "CLUSTER_NAME"
              value: "document-dataset-storage"
            - name: "NUMBER_OF_MASTERS"
              value: "3"
            - name: NODE_MASTER
              value: "true"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx256m"
            - name: "ES_PLUGINS_INSTALL"
              value: "https://github.com/NLPchina/elasticsearch-sql/releases/download/5.5.2.0/elasticsearch-sql-5.5.2.0.zip,repository-s3"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: BACKUP_S3_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: BACKUP_S3_SECRET_KEY
          ports:
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - emptyDir:
            medium: ""
          name: "storage"
