apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-apps-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: client-apps-ingress
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    cert-manager.io/issuer: client-apps-issuer
spec:
  tls:
    - hosts:
        - preproduction.resourcewatch.org
        - south-africa-platform.vizzuality.com
        - indonesia-platform-staging.vizzuality.com
        - india-platform-staging.vizzuality.com
      secretName: client-apps-certificate
  rules:
    - host: preproduction.resourcewatch.org
      http:
        paths:
          - path: /*
            backend:
              serviceName: nginx
              servicePort: 80
    - host: south-africa-platform.vizzuality.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: nginx
              servicePort: 80
    - host: indonesia-platform-staging.vizzuality.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: nginx
              servicePort: 80
    - host: india-platform-staging.vizzuality.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: nginx
              servicePort: 80