---
# Source: neo4j/templates/neo4j-restore.service.yaml
apiVersion: v1
kind: Service
metadata:
  name: neo4j-neo4j
  namespace: core
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "neo4j"
    helm.sh/chart: "neo4j-2.0.0"
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: core
spec:
  clusterIP: None
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
  selector:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/instance: "neo4j"
    app.kubernetes.io/component: core
