apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  labels:
    type: db-elastic
    component: elasticsearch
    role: client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: db-elastic
        component: elasticsearch
        role: client
    spec:
      initContainers:
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.5.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch-discovery"
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1g -Xmx1g"
        - name: "ES_PLUGINS_INSTALL"
          value: "https://github.com/NLPchina/elasticsearch-sql/releases/download/5.5.0.0/elasticsearch-sql-5.5.0.1.zip,repository-s3"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: BACKUP_S3_ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: BACKUP_S3_SECRET_KEY
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
