apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: ingest
spec:
  type: ClusterIP
  selector:
    component: elasticsearch
    role: ingest
  ports:
    - name: http
      port: 9200
      protocol: TCP
